### ISSUE TITLE
call to FundMe.getConversionRate errored: VM error: revert. I am stuck in this part I tried both injected Web3 and the VM but I can't  call the function get price

### ISSUE THREAD

**Issue by ChadiZarkal** [PatrickAlphaC/fund-me-fcc#10]
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.8;

import "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol";

contract FundMe {

    uint256 minimumUSD = 50;

    //function fund() public payable {
      //  require(msg.value >= minimumUSD ,"Dind't send enough" );
    //}

    function getPrice() public view returns (uint256){
        //	0x8A753747A1Fa494EC906cE90E9f37563A8AF630e
        AggregatorV3Interface priceFeed = AggregatorV3Interface(0x8A753747A1Fa494EC906cE90E9f37563A8AF630e);
        (,int256 price,,,) = priceFeed.latestRoundData();
        return uint256(price*1e18);
    }

    function getConversionRate(uint256 ethAmount) public view returns(uint256){
        uint256 ethprice  = getPrice();
        uint256 ethAmountinUsd = (ethprice*ethAmount)/1e18;
        return ethAmountinUsd;

    }

    //function withdraw() {}
}

**Comment by PatrickAlphaC** [comment]
Hi! Could you please follow the guide here on asking questions in the course?

https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be

And can you ask this in the discussions of the larger repo? Thanks!

https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
