### ISSUE TITLE
Withdrawal

### ISSUE THREAD

**Issue by czilauto0r1** [PatrickAlphaC/fund-me-fcc#12]
Hi, just started my adventure with that course love it, I had some problems before, everything solved but this time need some help.
So, no errors while compile, if I switch account which is no owner I'm getting message Sender is not owner! so that means it works but when I change back on owner account and click withdraw I'm getting gas estimation failed gas required exceeds allowance (29999972) and I can't withdraw. Here is my code sorry for that mess with comments but its helpful for me. (and english its my second language)

Here is my code: https://gist.github.com/czilauto0r1/055d4c8cfe1efa9080ace73da1d00162

**Comment by PatrickAlphaC** [comment]
Can you make a discussion on the full repo or check where your code differs with my code? Thank you!

https://github.com/PatrickAlphaC/fund-me-fcc

**Comment by rishabhkalra96** [comment]
Hi, i am also facing the above issue. I checked my code based on the video tutorial until 1:07:54:30 and also validated from the repo. On further debugging it seems, the call method is consuming way too much gas to withdraw then the 30000000 limit. i might be wrong though, is there a way to reduce this ?
