### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by aayushsaini-dev** [PatrickAlphaC/fund-me-fcc#18]
i am learning lesson 4 . but i dont get javascript(vm)

i have to do in **Remix vm.**     I did lesson 3 also in Remix vm .

now i want to deploy it in _javascript vm_ please somebody help me .****

**Comment by PatrickAlphaC** [comment]
Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
2. Follow this section for formatting questions? https://www.youtube.com/watch?t=19846&v=gyMwXuJrbJQ&feature=youtu.be
