### ISSUE TITLE
Payable in withdraw function.

### ISSUE THREAD

**Issue by yyc13236** [PatrickAlphaC/fund-me-fcc#21]
Hi, function withdraw() has the payable decorator.
is there a specific reason for this, or can I remove it.
And when withdrawing funds, do I have to cast msg.sender with payable ie., payable(msg.sender)? or can I remove it.
Thank you.

**Comment by PatrickAlphaC** [comment]
You're right! We can remove it! 

Yes, you do have to cast msg.sender to payable.

**Comment by yyc13236** [comment]
Thank you Patrick.
You a legend!
