### ISSUE TITLE
01-Deploy-fundme error

### ISSUE THREAD

**Issue by colonelxy** [PatrickAlphaC/fund-me-fcc#27]
I'm getting this error when I run deploy:
```

TypeError: Cannot read properties of undefined (reading 'ethUsdPriceFeed')
```

This is the line with a problem:
```

 } else {
        ethUsdPriceFeedAddress = networkConfig[chainId]["ethUsdPriceFeed"]
    }
```

Where could I be going wrong?

**Comment by PatrickAlphaC** [comment]
Thanks for this issue!

Can you:
1. Make this a discusson on the full repo? https://github.com/smartcontractkit/full-blockchain-solidity-course-js/
