### ISSUE TITLE
Error: File import callback not supported

### ISSUE THREAD

**Issue by Ashutsoh1729** [PatrickAlphaC/fund-me-fcc#28]
I have copy pasted the given code in this course and my code editor shows an error.
<img width="1280" alt="Screenshot 2022-10-25 at 9 56 15 PM" src="https://user-images.githubusercontent.com/99027378/197830048-6374d345-01ce-4d15-934f-87b3b0fa7cd8.png">
The same problem with the PriceConverter file
<img width="1280" alt="Screenshot 2022-10-25 at 9 57 21 PM" src="https://user-images.githubusercontent.com/99027378/197830280-be6ad6f0-0cca-4475-a3ab-f98a79e71451.png">

**Comment by pooolz** [comment]
Hey there, please try installing all the dependancies in the package.json file with yarn or npm. You will need ```@chainlink/contracts``` package in this specific case

**Comment by isfreddy** [comment]
# via Yarn
yarn add @chainlink/contracts
# via npm
npm install @chainlink/contracts --save

**Comment by shawnesquivel** [comment]
> # via Yarn
> yarn add @chainlink/contracts
> 
> # via npm
> npm install @chainlink/contracts --save

This worked for me! Thanks! 😁
