### ISSUE TITLE
Simple Ether to USD Converter Quetion

### ISSUE THREAD

**Issue by guangzhichen** [PatrickAlphaC/fund-me-fcc#31]
is that means sender shoud sent at lease 50 * 10 ** 18 USD ?
`uint256 public constant MINIMUM_USD = 50 * 10 ** 18;
require(msg.value.getConversionRate() >= MINIMUM_USD, "You need to spend more ETH!");`

**Comment by rockyko** [comment]
We use 10 ** 18 because Solidity doesn't fully support decimal numbers; it only deals with integers. It is like eliminating the 0s in PriceConverter.sol

**Comment by PatrickAlphaC** [comment]
Sorry on my delay here. Seems like @rockyko answered
