### ISSUE TITLE
ParserError: Expected ';' but got ',' 

### ISSUE THREAD

**Issue by Benedicity948** [PatrickAlphaC/fund-me-fcc#33]
ParserError: Expected ';' but got ','
  --> contracts/FundMe.sol:55:26:
   |
55 |         {bool callSuccess, } = payable(msg.sender).call{value: address(this).balance}("");
   |                          ^

I keep encountering this error every time in my contract. Please anyone with a solution.

**Comment by PatrickAlphaC** [comment]
You want `()` instead of `{}`

Change:

```
{bool callSuccess, } = payable(msg.sender).call{value: address(this).balance}("");
```

to:

```
(bool callSuccess, ) = payable(msg.sender).call{value: address(this).balance}("");
```

**Comment by Benedicity948** [comment]
Thank you for the clarity.
