### ISSUE TITLE
Error with Price Converter.sol

### ISSUE THREAD

**Issue by ShippingWars** [PatrickAlphaC/fund-me-fcc#5]
In lesson 4 I've created the price converter library, but when I deploy the contract and try to fund  it, it displays that I need to pay 75000000.36 ETH instead of the 50 USD? Any idea why im receiving this error? Attached is my workspace.

**Comment by PatrickAlphaC** [comment]
I removed your zip from the comment, I don't want people downloading zip files they are not familiar with.

Can you follow this video and update your question on [the main repo](https://github.com/smartcontractkit/full-blockchain-solidity-course-js)? (using the formatting techniques)
https://www.youtube.com/watch?v=XT8STflvwNo

**Comment by PatrickAlphaC** [comment]
Thank you!

**Comment by ShippingWars** [comment]
Understood. Thank you!
