### ISSUE TITLE
Error with fundme.sol

### ISSUE THREAD

**Issue by kchain18** [PatrickAlphaC/fund-me-fcc#6]
When trying to fund it, I noticed your video uses ^0.8.0, but your github file says ^0.8.8. When trying to fund the contract off the github, it didn't work. When trying to fund the contract after changing it to ^0.8.0 - it works

**Comment by PatrickAlphaC** [comment]
Could you try compiling with v 0.8.8 of solidity in your remix? Thanks for the issue!
