### ISSUE TITLE
Getting different result from you using addressToAmountFunded function

### ISSUE THREAD

**Issue by noob1ing** [PatrickAlphaC/fund-me-fcc#7]
I funded 0.03eth with the same address twice.
When I use the addressToAmountFunded function I don't get the total amount that I funded. Instead I get 1 fundings worth or 0.03eth. My array shows the same address at index 0 and 1.
When you did it you got the total amount that you funded.

Any ideas why it is different?

**Comment by PatrickAlphaC** [comment]
Would need more information, what were the exact steps you took to get here?

And could you make this a question on the full repo? Thanks! 
https://github.com/smartcontractkit/full-blockchain-solidity-course-js
